name: TokenEater
options:
  bundleIdPrefix: com.tokeneater
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  defaultLocalization: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "4.3.0"
    CURRENT_PROJECT_VERSION: "1"
    ARCHS: "arm64 x86_64"

targets:
  TokenEaterApp:
    type: application
    platform: macOS
    sources:
      - path: TokenEaterApp
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokeneater.app
        PRODUCT_NAME: TokenEater
        CODE_SIGN_ENTITLEMENTS: TokenEaterApp/TokenEaterApp.entitlements
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_CFBundleDisplayName: TokenEater
        INFOPLIST_KEY_LSUIElement: YES
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: TokenEaterWidgetExtension
        embed: true

  TokenEaterTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TokenEaterTests
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokeneater.tests
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"

  TokenEaterWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: TokenEaterWidget
        excludes:
          - Info.plist
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokeneater.app.widget
        PRODUCT_NAME: TokenEaterWidgetExtension
        CODE_SIGN_ENTITLEMENTS: TokenEaterWidget/TokenEaterWidget.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks"
    info:
      path: TokenEaterWidget/Info.plist

schemes:
  TokenEaterTests:
    build:
      targets:
        TokenEaterTests: [test]
    test:
      config: Debug
      targets:
        - TokenEaterTests

  TokenEaterApp:
    build:
      targets:
        TokenEaterApp: all
        TokenEaterWidgetExtension: all
    run:
      config: Debug
    archive:
      config: Release
